### ISSUE TITLE
app crashes with cryptic error message (probably because SD card is readonly?)

### ISSUE THREAD

**Issue by binary1230** [CHDKUtil/CHIMP#8]
ran, attempting install of CHDM on a 16GB SD card for a Canon Powershot G12

wizard gets to the install part and fails with this error:
![image](https://user-images.githubusercontent.com/5413064/125146548-49d0e100-e0f4-11eb-869a-2b2254c85561.png)

stack trace is:

```
 at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Chimp.Device.WriteBlock(SafeFileHandle hDevice, Byte[] buffer, UInt32 size) in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Device.cs:line 42
   at Chimp.Services.PartitionService.CreatePartitions(String driveLetter) in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Services\PartitionService.cs:line 82
   at Chimp.Services.InstallService.CreatePartitions() in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Services\InstallService.cs:line 52
   at Chimp.Installers.Installer.CreatePartitions() in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Installers\Installer.cs:line 189
   at Chimp.Installers.Installer.CopyPartition() in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Installers\Installer.cs:line 163
   at Chimp.Installers.Fat32Installer.Install(CancellationToken cancellationToken) in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Installers\Fat32Installer.cs:line 26
   at Chimp.Installers.Installer.<>c__DisplayClass44_0.<InstallAsync>b__0() in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Installers\Installer.cs:line 69
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Chimp.Installers.Installer.<InstallAsync>d__44.MoveNext() in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Installers\Installer.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Chimp.Controllers.InstallController.<InstallAsync>d__13.MoveNext() in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Controllers\InstallController.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Chimp.Controllers.InstallController.<EnterStepAsync>d__11.MoveNext() in D:\projects\external\CHIMP\src\CHIMP\CHIMP\Controllers\InstallController.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Chimp.MainWindow.<OnSelectedIndexChangedAsync>d__35.MoveNext() in D:\projects\external\CHIMP\src\CHIMP\CHIMP\MainWindow.xaml.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Chimp.MainWindow.<Step_PropertyChanged>d__24.MoveNext() in D:\projects\external\CHIMP\src\CHIMP\CHIMP\MainWindow.xaml.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Only after staring at this for a bit did I try another program, and then I realized I'm -pretty sure- I have the lock on the SD card because I'm dumb, and about to test that.  Also, STICK fails and reports this when I run it, so guessing that's probably it:
![image](https://user-images.githubusercontent.com/5413064/125146577-7dac0680-e0f4-11eb-89f2-48bf7eeb5cbc.png)

I think this probably should fail then, but the error message could just be a bit more user-friendly, maybe print some logs with the stack trace somewhere? Maybe we can give the user a hint about where to look for the solution.

I'll attempt to trace this down a bit more after dinner, if it's easy I'll throw in a pull request.

Thanks for you work on this tool!

**Comment by binary1230** [comment]
the last screen with the error message on it is this:
![image](https://user-images.githubusercontent.com/5413064/125146664-ee532300-e0f4-11eb-81d0-1331734dcaf5.png)

then the app immediately exits when I click the OK on the messagebox

**Comment by binary1230** [comment]
My issue is a loose nut between the chair and the keyboard.
er, I mean, 

YES: my SD card is mounted as a read only filesystem (if I go into windows explorer, I can't write any files to it). so that should mean the install SHOULD fail to install

So what I think the resolution on this issue should be is:

Repro steps:
1. Insert a readonly SD card (lock the slider on the physical card)
2. go through the wizard
3. hit install on CHDK, which will fail

EXPECTED: Installation gives me an error message along the lines of "dude, you ... uh... need to not have a readonly memory card, obviously. c'mon now.  I know it's been a while since your last coffee but, seriously"
ACTUAL: Installation gives a pretty cryptic messagebox with: "Error 0x8007045D, The request could not be performed because of an I/O device error."


----
more info:

here's the exception thrown:
![image](https://user-images.githubusercontent.com/5413064/125150155-9d9af480-e10b-11eb-9015-095fe031382e.png)


couple ideas on how to best solve this, one or any of these might help:

1. (maybe the easier version, less elegant)
the line that fails is "Device.WriteBlock(hDevice, buffer, sectorSize);" for me in PartitionService.CreatePartitions()

maybe we could wrap that in a try/catch, raise a new exception with the original COMException as inner, and add an error message hint there with something about "check if the disk is readonly?"



2.  throw an exception earlier, and maybe also wrap that exception as well.

Device.OpenReadWrite() returns a SafeFileHandle.  that sounds like a function that should not work if the handle isn't writeable, but, currently, hDevice.IsValid is (surprisingly) true!

under the hood that's doing:

```c#
var hDevice = CreateFile(deviceName,
 EAccessMode.Read | EAccessMode.Write, EShareMode.Read | EShareMode.Write,
 IntPtr.Zero, ECreationDisposition.OpenExisting, 0, IntPtr.Zero);
```

it would seem like if we passed in EAccessMode.Write and the file hand't isn't writeable, it should have errored. but it doesn't and instead the place where we actually fail to write is where the exception is thrown.

it might be the case that there's no way to know that Device.WriteBlock() (which calls kernel32.dll's ```WriteFile()```) will fail until it's tried, but, maybe there's some flags that are wrong here or similar (maybe the share mode flags might have something to do with it, I can't remember)

yea actually... digging around there might be some stuff in the ioctl that could help here (this is new territory for me) called ```DISK_ATTRIBUTE_READ_ONLY``` which we can query, that might be a good check to bail early if it can tell if the filesystem is readonly. I'll have a look at that next

**Comment by binary1230** [comment]
I might come back to this if I have time, looks like something like this could be worth looking at, the GetOnlineStatus() is basically what we might need here.
https://stackoverflow.com/questions/63100137/how-to-detect-whether-physical-device-is-online-or-offline-in-windows-using-pinv

**Comment by dmitry-shechtman** [comment]
> https://stackoverflow.com/questions/63100137/how-to-detect-whether-physical-device-is-online-or-offline-in-windows-using-pinv

Alas, Attributes are always 0 on my system. However, the following seems to work:

```C#
    bool IsReadOnly(CardInfo cardInfo)
    {
        using (var searcher = new ManagementObjectSearcher($"SELECT * FROM Win32_LogicalDisk WHERE DeviceID='{cardInfo.DriveLetter}'"))
        using (var disks = searcher.Get())
        {
            var disk = disks.Cast<ManagementObject>().SingleOrDefault();
            var access = (ushort?)disk?.GetPropertyValue("Access");
            return access == 0x0001;
        }
    }
```

Although CHIMP is in maintenance mode, I might consider a pull request.
